server:
  port: 8080

spring:
  application:
    name: GDPRGateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        - id: anagrafica-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/anagrafica/**
        - id: dpo-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/dpo/**
        - id: utente-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/utente/**
        - id: documenti-dpo
          uri: http://localhost:8082
          predicates:
            - Path=/api/documenti/dpo/**
        - id: documenti-utente
          uri: http://localhost:8082
          predicates:
            - Path=/api/documenti/utente/**
        - id: documenti-dati
          uri: http://localhost:8082
          predicates:
            - Path=/api/documenti/dati/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

app:
  jwt:
    secret: AnRLv2aSazie0dCbjSpITbqOE4fjPYuYkTNPrBHFzpk=
    expiration: 3600000

management:
  endpoints:
    web:
      exposure:
        include: health,info
